<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BLRL-CFN8S73" failures="3" tests="5" name="Login Test ff" time="60.035" errors="0" timestamp="2021-08-16T10:00:26 IST">
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="1.994"/>
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="3.092"/>
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="7.086">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="4.903">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="7.992">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
</testsuite> <!-- Login Test ff -->
