<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BLRL-CFN8S73" failures="3" tests="5" name="Login Test ch" time="60.095" errors="0" timestamp="2021-08-16T09:59:26 IST">
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="1.954"/>
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="6.293"/>
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="5.959">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="5.925">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="6.034">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
</testsuite> <!-- Login Test ch -->
